### PR TITLE
Added project "Bart van der Leck"

### PR DESCRIPTION
**Pull request by piixelcat**
Added documention for "Bart van der Leck" to the project folder.

### CODE REVIEW

**Comment by fabianmoronzirfas** [comment]
- What about the image usage rights? This will be publicly available online. You should reference the original author and see if you can use them
- Please loose the I. Write on a more abstract level.  
- The code examples should not be in a subfolder of the project. Please add them as own sketches ([see ->](https://github.com/fabianmoronzirfas/gestalten-in-code/wiki/Contributing-Projects#code)) to the collection of sketches. As [this guide](https://github.com/fabianmoronzirfas/gestalten-in-code/wiki/Contributing-P5js-Sketches) discribes and you already did.  

btw:  

> The title of your project will be inserted at the top as `h1`, in Markdown `#`. Don't add it again.
[Contributing-Projects#markdown-files--syntax](https://github.com/fabianmoronzirfas/gestalten-in-code/wiki/Contributing-Projects#markdown-files--syntax)

**Comment by fabianmoronzirfas** [comment]
Awesome. @piixelcat @edgalindo great work you did there! 🎉

**Comment by fabianmoronzirfas** [comment]
@piixelcat please fix isse #34

**Comment by fabianmoronzirfas** [comment]
Your projects are live https://interface.fh-potsdam.de/gestalten-in-code/projects/ please review for any mistakes (ping @edgalindo )

**Comment by piixelcat** [comment]
Found two small mistakes:
- The headline underneath "Analysis" seems to be broken but looks correct in Markdown
- In chapter "Primary colors": "colors." drops under the image although there's no paragraph

screenshot

**Pull request merged**
